//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterManager.Control.DBControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int ID { get; set; }
        public int LecID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public bool Attend { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Lecture Lecture { get; set; }
        public virtual Student Student { get; set; }
    }
}
