//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterManager.Control.DBControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.StudentBooks = new HashSet<StudentBook>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Class { get; set; }
        public Nullable<double> Price_for_St { get; set; }
        public Nullable<double> Price { get; set; }
        public int Quantity { get; set; }
        public Nullable<double> Total { get; set; }
        public int SubjectID { get; set; }
        public string Note { get; set; }
    
        public virtual Class Class1 { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentBook> StudentBooks { get; set; }
    }
}
