//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterManager.Control.DBControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamDetail()
        {
            this.StudentExams = new HashSet<StudentExam>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int ExamID { get; set; }
        public double Mark { get; set; }
    
        public virtual Exam Exam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentExam> StudentExams { get; set; }
    }
}
