//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterManager.Control.DBControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentExam
    {
        public int ID { get; set; }
        public int STID { get; set; }
        public int ExamID { get; set; }
        public Nullable<int> QID { get; set; }
        public double Mark { get; set; }
    
        public virtual ExamDetail ExamDetail { get; set; }
        public virtual Exam Exam { get; set; }
        public virtual Student Student { get; set; }
    }
}
