//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterManager.Control.DBControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentBook
    {
        public int ID { get; set; }
        public int BookID { get; set; }
        public int STID { get; set; }
        public int Number { get; set; }
        public float Discount { get; set; }
        public float BeforeDiscount { get; set; }
        public float AfterDiscount { get; set; }
        public float Paid { get; set; }
        public float Remainder { get; set; }
        public string Date { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Student Student { get; set; }
    }
}
