//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterManager.Control.DBControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersPermission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsersPermission()
        {
            this.Users1 = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public bool MainPage { get; set; }
        public bool Students { get; set; }
        public bool AddStudent { get; set; }
        public bool Subjects { get; set; }
        public bool EditClasses { get; set; }
        public bool ShowStudents { get; set; }
        public bool Groups { get; set; }
        public bool AddGroup { get; set; }
        public bool StudentGroups { get; set; }
        public bool ViewAllGroups { get; set; }
        public bool Attendance { get; set; }
        public bool TakeAttendance { get; set; }
        public bool ViewAttendance { get; set; }
        public bool Books { get; set; }
        public bool AddBook { get; set; }
        public bool ViewBooks { get; set; }
        public bool StudentBooks { get; set; }
        public bool Exams { get; set; }
        public bool AddExam { get; set; }
        public bool ViewExams { get; set; }
        public bool CorrentExams { get; set; }
        public bool Users { get; set; }
        public bool AddUser { get; set; }
        public bool EditUsers { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users1 { get; set; }
    }
}
