//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterManager.Control.DBControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string CardNumber { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int PermissionsID { get; set; }
        public byte[] Image { get; set; }
    
        public virtual UsersPermission UsersPermission { get; set; }
    }
}
